# Generated by Django 5.0.4 on 2024-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_higlighted_snippet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='higlighted',
        ),
        migrations.AddField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
