# Generated by Django 5.0.4 on 2024-07-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_snippet_higlighted_snippet_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='linenos',
            field=models.BooleanField(default=True),
        ),
    ]
