# Generated by Django 5.0.4 on 2024-07-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_linenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
