# Generated by Django 5.0.4 on 2024-07-23 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_sharedsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedsnippet',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedsnippet',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_snippet', to='snippets.snippet'),
        ),
    ]
