# Generated by Django 5.0.4 on 2024-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
